apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nginx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/nfs/data
    server: 172.16.8.199
